// <auto-generated />
using EmployeeManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManager.Migrations
{
    [DbContext(typeof(EmplManagerDbContext))]
    [Migration("20210521124053_InsertEmployeeTable")]
    partial class InsertEmployeeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeManager.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeDbSet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 1,
                            Email = "michel@logient.ca",
                            Name = "Michel"
                        },
                        new
                        {
                            Id = 2,
                            Department = 1,
                            Email = "adrien@logient.ca",
                            Name = "Adrien"
                        },
                        new
                        {
                            Id = 3,
                            Department = 1,
                            Email = "sophie@logient.ca",
                            Name = "Sophie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
